name: MooTools Unobtrusive Background Image Switcher
author: bcat
category: effects
tags: [animation, background, full screen, preload, unobtrusive]
#docs: http://www.bcat.eu/blog/mootools-unobtrusive-background-image-switcher/
#demo: http://www.bcat.eu/data/demo/bg-switcher/fullscreen/